name: elephant
dependencies:
- libgfortran=1.0=0
- alabaster=0.7.7=py35_0
- babel=2.2.0=py35_0
- docutils
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- mkl=11.3.1=0
- numpy
- numpydoc
- openssl=1.0.2g=0
- pip=8.1.1=py35_0
- pygments=2.1.1=py35_0
- python=3.5.1=0
- pytz=2016.2=py35_0
- readline=6.2=2
- scipy=0.17.0=np110py35_0
- setuptools=20.3=py35_0
- six=1.10.0=py35_0
- scikit-learn==0.17.1
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - neo
  - quantities
  - sphinx-rtd-theme
 
