name: elephant

channels:
  - conda-forge  # required for MPI

dependencies:
  - python>=3.8
  - pip
  - mpi4py
  - numpy
  - scipy
  - tqdm
  - pandas
  - scikit-learn
  - statsmodels
  - jinja2
  - pip:
     - -r file:requirements.txt
