name: elephant

channels:
  - conda-forge  # required for MPI

dependencies:
  - python>=3.6
  - mpi4py
  - numpy
  - scipy
  - tqdm
  - pandas
  - scikit-learn
  - statsmodels
  - jinja2
  #- pip:
    # - viziphant
    # viziphant can be removed once it is integrated into requirements-tutorials.txt
