name: elephant

channels:
  - conda-forge  # required for MPI and pandoc

dependencies:
  - python>=3.9
  - mpi4py
  - openmpi
  - pandoc
  - libstdcxx-ng
  - pip:
    - -r requirements.txt
    - -r requirements-extras.txt
    - -r requirements-docs.txt
    - -r requirements-tutorials.txt
