name: elephant

channels:
  - conda-forge  # required for MPI

dependencies:
  - python>=3.9
  - mpi4py
  - pip:
    - -r requirements.txt
    - -r requirements-extras.txt
    - -r requirements-tutorials.txt
