name: elephant

channels:
  - conda-forge  # required by mpi4py

dependencies:
  - python>=3.6
  - pip
  - mpi4py
  - numpy
  - scipy
  - tqdm
  - pandas
  - scikit-learn
  - statsmodels
  - pip:
     - -r file:requirements.txt
