name: elephant

channels:
  - conda-forge  # required for MPI and pandoc

dependencies:
  - python=3.12  # pinned cause >=3.13 breaks matplotlib<3.9 (RecursionError)
  - pip  # explicitly adding pip to ensure mamba uses env pip, not base one
  - mpi4py
  - openmpi
  - pandoc
  - libstdcxx-ng
  - pip:
    - -r requirements.txt
    - -r requirements-extras.txt
    - -r requirements-docs.txt
    - -r requirements-tutorials.txt
