name: elephant

channels:
  - conda-forge  # required for MPI

dependencies:
  - python>=3.9
  - mpi4py
  - openmpi
  - pip:
    - -r requirements.txt
    - -r requirements-extras.txt
    - -r requirements-tests.txt
