name: Build Wheels

# Trigger the workflow on push to master. (this is equal to: PR is merged)
on:
  push:
    branches:
      - master
  pull_request_review:
    types: [ submitted ]
  pull_request:
    branches:
      - master
    types:
      - synchronize

# Building wheels on Ubuntu, Windows and MacOS systems
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.3.1

      - name: Install libomp
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Build wheels (Linux / Windows)
        if: runner.os != 'macOS'
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp38-*"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"
          CIBW_ARCHS: "auto64"

      - name: Build wheels (macOS)
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build --wheel --outdir wheelhouse
        env:
          LDFLAGS: "-L/opt/homebrew/opt/libomp/lib ${{ env.LDFLAGS }}"
          CPPFLAGS: "-I/opt/homebrew/opt/libomp/include ${{ env.CPPFLAGS }}"
          CPLUS_INCLUDE_PATH: "/opt/homebrew/opt/libomp/include:${{ env.CPLUS_INCLUDE_PATH }}"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
  merge_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-wheels
          pattern: wheels-*
