name: Build Wheels

# Triggers for the workflow (PR review submission and merge to master)
on:
  push:
    branches: [ master ]
  pull_request_review:
    types: [ submitted ]
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

# Building wheels on Ubuntu, Windows and MacOS systems
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: pip install cibuildwheel==3.3.1

      - name: Setup OpenMP for macOS and set deployement target
        if: runner.os == 'macOS'
        run: |
          brew install libomp
          OMP_PATH=$(brew --prefix libomp)
          echo "LDFLAGS=-L${OMP_PATH}/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I${OMP_PATH}/include" >> $GITHUB_ENV
          if [ "$RUNNER_ARCH" = "ARM64" ]; then
            echo "MACOSX_DEPLOYMENT_TARGET=15.0" >> $GITHUB_ENV
          else
            echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV
          fi

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: "auto"
          CIBW_SKIP: cp38-*

      - name: Verify wheels contain compiled code
        run: |
          # Download elephant and deps wheels to a DIR
          mkdir -p localwheels
          pip wheel --wheel-dir localwheels .

          # Remove downloaded elephant and copy wheeels from cibuildwheel
          rm localwheels/elephant*.whl
          cp wheelhouse/elephant*.whl localwheels/

          # Install elephant and deps from local wheels and check for spade
          pip install --no-index --find-links localwheels elephant
          cd $HOME
          python -c "from elephant.spade_src import fim"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  merge_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-wheels
          pattern: wheels-*
